Vonage/vonage-video-react-app

.github/workflows/check-pull-request-title.yml, .github/workflows/lint.yml
This PR fixes the issue where updating the incorrect title does not re-trigger the job unless a new commit is pushed up or the PR is closed/reopened.
I moved out the job to check the PR title out of lint job to its own job since we do not want to trigger all of the lint to re-run if the PR title is changed.
Create a new branch from this branch and make a small change to, for example, README.md.
Make a new pull request with your newly created branch with a PR title that would not satisfy the conditions. 
Notice that `check-pull-request-title` job fails.
Change the PR title to the correct format such as `VIDCS-3248: testing the pull request`
Notice that after some seconds the `check-pull-request-title` job runs and passes.
Resolves …
=> VIDCS-3248: Updating title does not re-run the CI job

backend/package.json, frontend/package.json, integration-tests/tests/multiparty.spec.ts, package.json, yarn.lock
- Fix dependency security issues flagged in #1 and #2 by mend-for-github
- Fix a failing integration test
- Check that mend CI check passes
- Check tests pass
Resolves [VIDCS-3205](https://jira.vonage.com/browse/VIDCS-3205)
=> VIDCS-3205: Fix deps security issues with resolutions

.github/workflows/check-pull-request-title.yml
This PR resolves the 2 issues mentioned in the `Issues` tab:
https://github.com/Vonage/vonage-video-react-app/issues/11
https://github.com/Vonage/vonage-video-react-app/issues/10
We need to make sure that with these changes the `check-pull-request-title.yml` job still runs; therefore, please follow the steps [described here](https://github.com/Vonage/vonage-video-react-app/pull/8) to make sure it still works. 
Resolves [VIDCS-3140](https://jira.vonage.com/browse/VIDCS-3140)
[👎 ] Resolves a `Known Issue`.
[👍 ] Resolves an item reported in `Issues`.
If yes, which issue? 
* [Issue Number 11](https://github.com/Vonage/vonage-video-react-app/issues/11)
* [Issue Number …
=> VIDCS-3140: Resolve GitHub Mend warnings for VERA

frontend/src/components/MeetingRoom/AudioInputOutputDevices/AudioInputOutputDevice.spec.tsx, frontend/src/components/MeetingRoom/AudioInputOutputDevices/ReduceNoiseTestSpeakers/ReduceNoiseTestSpeakers.tsx, frontend/src/utils/util.ts
- Removes sound test / speaker test option on android
- This fixes a bug where opening mic audio device settings crashed the app because it tried to use `setSinkId` which is not supported
```
index-s-hJiPSy.js:40 TypeError: i.setSinkId is not a function
index-s-hJiPSy.js:1954 Uncaught TypeError: i.setSinkId is not a function
index-s-hJiPSy.js:620 OpenTok:NativeVideoElementWrapper:2:warn Video element paused, auto-resuming. If you intended to do this, use publishVideo(false) or subscribeToVideo(false) instead. +0ms
index-s-hJiPSy.js:1954 Uncaught (in promise) 
p {code: undefined, message: 'setAudioOutputDevice is not supported in your browser.', name: 'OT_UNSUPPORTED_BROWSER', stack: 'Error: setAudioOutputDevice is not supported in yo…/localhost:3345/assets/index-s-hJiPSy.js:81:7215)'}
``` …
=> VIDCS-3223: Fix audio option crash in android chrome - disable speaker test on android

backend/server.ts
This PR adds an instruction to our express server to not be indexed by the search engines. 
Checkout this branch locally.
Run the backend by doing `yarn start:backend`
Run `curl -I http://localhost:3345`
Make sure the following tag is present: 
```
X-Robots-Tag: noindex, nofollow
```
Resolves [VIDCS-3247](https://jira.vonage.com/browse/VIDCS-3247)
[👎 ] Resolves a `Known Issue`.
[👎 ] Resolves an item reported in `Issues`.
=> VIDCS-3247: Stop VERA instance being indexed

.github/workflows/run-tests.yml
Skip Sonarcloud scan and Integration tests if PR is from a fork (External)
I added this change to [this PR](https://github.com/Vonage/vonage-video-react-app/pull/4) which I created from my personal test github account (a an external contributor).
And the[ jobs are getting skipped ](https://github.com/Vonage/vonage-video-react-app/actions/runs/12931347172/job/36065065889?pr=4)
Which I believe should be enough testing for the PR
Resolves [VIDCS-3281](https://jira.vonage.com/browse/VIDCS-3281)
=> VIDCS-3281: Skip Sonarcloud scan and Integration tests if PR is from a fork (External Contributor)

.github/workflows/deploy-to-vcr.yml
This PR updates the VCR deployment job to trigger automatically upon merges to the develop branch, enabling dogfooding and testing of the develop branch before releasing or merging into the main branch.
n/a
Resolves [VIDCS-3289](https://jira.vonage.com/browse/VIDCS-3289)
=> VIDCS-3289: Update the Vera deploy to VCR job to trigger on merge to develop

.github/workflows/auto-set-base.yml
This PR adds a GHA job to make develop as the base branch of the PR only on opening the PR. Which will acts as the default moving forward.
Also, we can re-change the default branch once the job is done to whatever we want. 
Notice below the default of this branch is changed to develop by bot
[Logs to the job before the last commit to make it run only on opening the PR
](https://github.com/Vonage/vonage-video-react-app/actions/runs/12948395663/job/36116971265)
Resolves [VIDCS-3286](https://jira.vonage.com/browse/VIDCS-3286)
[ ] If yes, did you close the …
=> VIDCS-3286: Auto-set Base Branch to Develop

backend/package.json, frontend/package.json, package.json, yarn.lock
This PR updates "`axios`" to "`^1.7.8`", which is a vulnerability on the [Security check](https://github.com/Vonage/vonage-video-react-app/pull/31/checks?check_run_id=36377786013)
CI should Pass
Resolves [VIDCS-3330](https://jira.vonage.com/browse/VIDCS-3330)
=> VIDCS-3330: Fix WhiteSource Security Check failures

.github/workflows/auto-set-base.yml, .github/workflows/check-pull-request-title.yml, .github/workflows/deploy-to-vcr.yml, .github/workflows/run-tests.yml, backend/package.json, backend/tests/blockCallsForArgs.test.ts, frontend/package.json, frontend/src/components/MeetingRoom/ChatInput/ChatInput.spec.tsx, frontend/src/components/MeetingRoom/ChatInput/ChatInput.tsx, package.json, yarn.lock
Merge Develop to main.
n/a
Resolves [VIDCS-3292](https://jira.vonage.com/browse/VIDCS-3292)
=> VIDCS-3292: Push the new workflow and fixes to main

frontend/package.json, frontend/src/Context/AudioOutputProvider/useAudioOutput/useAudioOutput.spec.tsx, frontend/src/Context/AudioOutputProvider/useAudioOutput/useAudioOutput.tsx, frontend/src/Context/tests/RoomContext.spec.tsx, frontend/src/components/MeetingRoom/AudioInputOutputDevices/AudioInputOutputDevice.spec.tsx, frontend/src/components/MeetingRoom/AudioInputOutputDevices/AudioInputOutputDevices.tsx, frontend/src/components/MeetingRoom/AudioInputOutputDevices/InputDevices/InputDevices.tsx, frontend/src/components/MeetingRoom/AudioInputOutputDevices/OutputDevices/OutputDevices.tsx, frontend/src/components/MeetingRoom/AudioInputOutputDevices/ReduceNoiseTestSpeakers/ReduceNoiseTestSpeakers.tsx, frontend/src/components/SoundTest/SoundTest.spec.tsx, frontend/src/components/SoundTest/SoundTest.tsx, frontend/src/components/WaitingRoom/ControlPanel/ControlPanel.tsx, frontend/src/hooks/useDevices.tsx, frontend/src/utils/mockData/device.ts, yarn.lock
- Fixes crash when selecting audio output device in waiting room on android
- Change UI to allow audio output UI even when not supported by showing "System Default" and allowing Test Speaker to run
- Need to test quite thoroughly on different browsers including android and iOS
- Test audio output UI in waiting room
- Test Speaker Test in waiting room
- Test audio output UI in Meeting Room
- Test Speaker Test in Meeting Room
On supported devices:
- set non-default audio output device
- unplug device
- open audio settings
- expect new device (default) to be selected
Resolves [VIDCS-3273](https://jira.vonage.com/browse/VIDCS-3273)
If yes, which issue? …
=> VIDCS-3273: Fix audio output selection crash in android Waiting Room

.github/pull_request_template.md, docs/CONTRIBUTING.md
Update contributing doc to Reflect New Develop Branch Workflow.
See new[ contributing doc](https://github.com/Vonage/vonage-video-react-app/blob/VIDCS-3291-update-contributing-doc/docs/CONTRIBUTING.md) and [PR template](https://github.com/Vonage/vonage-video-react-app/blob/VIDCS-3291-update-contributing-doc/.github/pull_request_template.md)
n/a
Resolves [VIDCS-3291](https://jira.vonage.com/browse/VIDCS-3291)
=> VIDCS-3291: Update contributing doc to Reflect New Develop Branch Workflow

frontend/src/components/MeetingRoom/VideoTileCanvas/VideoTileCanvas.tsx, frontend/src/pages/MeetingRoom/MeetingRoom.spec.tsx, frontend/src/pages/MeetingRoom/MeetingRoom.tsx
- Adds a loading spinner while the session connects
- Helps with issue where it appears you're alone in the room but really you're still connecting
- run locally, test on slow and fast networks
- spinner should not appear during reconnections
Resolves [VIDCS-3274](https://jira.vonage.com/browse/VIDCS-3274)
=> VIDCS-3274: Add spinner while session connects

docs/KNOWN_ISSUES.md, frontend/package.json, frontend/src/utils/util.spec.tsx, frontend/src/utils/util.ts, yarn.lock
For MS Tablets, several buttons in the meeting room were missing because our `isMobile` utility was falsely reporting the device as mobile. To make mobile device detection easier, let's use the [`ua-parser-js`](https://docs.uaparser.dev/api/main/overview.html) library.
This PR changes the `isMobile` function to use `ua-parser-js`, and adds a few tests.
- grab a MS tablet
- go to the meeting room
- notice there's some buttons missing - should be all but the exit, and audio/video controls
- on your MS tablet, go to the meeting room
- it should have no missing buttons 🤞 
- additionally, please check with a mobile device or two and ensure the expected buttons are still missing
Resolves [VIDCS-2829](https://jira.vonage.com/browse/VIDCS-2829)
[✅] Resolves a `Known Issue`. …
=> VIDCS-2829: Vera - Meeting Rooms on Windows browsers are missing functionality buttons

frontend/package.json, yarn.lock
Bumping JS SDK version
- CI passes
Resolves [VIDCS-3348](https://jira.vonage.com/browse/VIDCS-3348)
=> VIDCS-3348: Bump VERA to use JS SDK 2.29.0

backend/package.json, frontend/package.json, integration-tests/package.json, package.json
Bumping VERA to 1.0.1
- CI passes
Resolves [VIDCS-3363](https://jira.vonage.com/browse/VIDCS-3363)
=> VIDCS-3363: Bump VERA version to 1.0.1

frontend/src/components/MeetingRoom/AudioIndicator/AudioIndicator.tsx
Fixes a tiny issue where the `onclick` handler was on an icon, not the button. This caused the browser console to log an error.
- checkout develop
- join a room with a user, open the browser console
- join the same room in another tab
- notice in the browser console, there's a an error
- repeat steps above, but hopefully the error isn't present 🤞 
Resolves [VIDCS-3370](https://jira.vonage.com/browse/VIDCS-3370)
=> VIDCS-3370: Onclick listener is on an icon, not the button

.github/workflows/update-screenshots.yml
Adding VIDEO_SERVICE_PROVIDER, VONAGE_APP_ID and VONAGE_PRIVATE_KEY to update screenshots job
It should have been a part of [this PR](https://github.com/Vonage/vonage-video-react-app/pull/33) but I missed to add these on the `update-screenshots` job.
n/a
Resolves [VIDCS-3373](https://jira.vonage.com/browse/VIDCS-3373)
=> VIDCS-3373: Add VIDEO_SERVICE_PROVIDER, VONAGE_APP_ID and VONAGE_PRIVATE_KEY to update screenshots job

.github/workflows/run-tests.yml
CI wasn't running due to a deprecated library version of `actions/cache` being run. This was due to an old sonarcloud action. This PR updates the sonarcloud action.
- CI passes 🤞 
Resolves [VIDCS-3387](https://jira.vonage.com/browse/VIDCS-3387)
=> VIDCS-3387: CI tests not running due to deprecated actions/cache

.github/workflows/run-tests.yml
CI wasn't running due to a deprecated library version of `actions/cache` being run. This was due to an old sonarcloud action. This PR updates the sonarcloud action.
- CI passes 🤞 
Resolves [VIDCS-3387](https://jira.vonage.com/browse/VIDCS-3387)
=> VIDCS-3387: CI tests not running due to deprecated actions/cache #2

frontend/src/components/MeetingRoom/VideoTileCanvas/VideoTileCanvas.tsx
There was an issue where the tiles of participants who were not the active speaker would be cut off on mobile. This PR fixes it.
- checkout develop or go to the live link
- join a meeting room on mobile and desktop *with videos on*
- notice on mobile, the preview publisher is cut off
- join a meeting room on mobile and desktop *with videos on*
- notice on mobile, both tiles are visible 🙌
Resolves [VIDCS-3375](https://jira.vonage.com/browse/VIDCS-3375)
If yes, which issue? [Issue Number](https://github.com/Vonage/vonage-video-react-app/issu …
=> VIDCS-3375: Video tiles hidden under toolbar on mobile

frontend/src/components/WaitingRoom/VideoLoading/VideoLoading.tsx
Fixes the (horizontal) scrollbar issue and the preview publisher width issue. Sorry for no screenshots, it's difficult to capture in the less than 1s that it appears.
- checkout develop or use the live app
- go to a waiting room
- notice before the publisher preview appears, there's a horizontal scrollbar
- you may need to refresh to catch this, as it's there for an instant. It's most easily noticeable if you've visited the live app through your mobile device as the autofill will cause your device to scroll to the left (on iOS Safari at least)
- go to a waiting room
- notice there's *no* horizontal scrollbar
Resolves [VIDCS-3111](https://jira.vonage.com/browse/VIDCS-3111)
[ ] …
=> VIDCS-3111: scrollbars appear for an instant and preview publisher is not full width in mobile waiting room

frontend/src/App.css
Emojis being rendered off-screen created an instant where scrollbars were present. Let's render them at the bottom, not below it.
- on `develop` or the live app
- go to a meeting room
- send some emojis
- notice there's scrollbars
- go to a meeting room
- send some emojis
- notice there's no scrollbars
Resolves [VIDCS-3391](https://jira.vonage.com/browse/VIDCS-3391)
=> VIDCS-3391: Scroll bars appear when reactions are sent

frontend/src/components/WaitingRoom/VideoContainer/VideoContainer.tsx, frontend/src/pages/WaitingRoom/WaitingRoom.tsx
Fixes the regression that Mike found in the waiting room on very large monitors.
- using the dev tools, expand your viewport to `572 x 1476`
- see there's no funky overlap
- expand viewport to max
- shrink viewport, ensuring no funkiness present visually
- check on a mobile device for good measure
- create a new meeting room and enter on desktop
- join waiting room on mobile
- note the preview publisher
- join the meeting room
- on desktop, ensure the meeting room subscriber more-or-less matches the mobile preview publisher
Resolves [VIDCS-3435](https://jira.vonage.com/browse/VIDCS-3435)
[ ] If yes, did you remove the item from the …
=> VIDCS-3435: Issue with waiting room on extra-wide viewports

frontend/src/components/GoodBye/GoodbyeMessage/GoodbyeMessage.tsx, frontend/src/pages/GoodBye/GoodBye.tsx
Removes some horizontal scroll on the goodbye page for mobile
- on a mobile device or use mobile view, go to the goodbye page, `/goodbye`
- notice there's a horizontal scrollbar
- on a mobile device or use mobile view, go to the goodbye page, `/goodbye`
- notice there's no horizontal scrollbar
- open `/goodbye` on your desktop
- drag your window to reduce your viewport until it's as small as it can get (see gif at bottom of comments)
Resolves [VIDCS-3319](https://jira.vonage.com/browse/VIDCS-3319)
If yes, which issue? [Issue …
=> VIDCS-3319: In goodbye page on mobile, the webpage is scrollable

frontend/package.json, yarn.lock
Bump @vonage/client-sdk-video to 2.29.1
- check things work including blur
Resolves [VIDCS-3445](https://jira.vonage.com/browse/VIDCS-3445)
=> VIDCS-3445: Bump @vonage/client-sdk-video to 2.29.1

.eslintrc
This PR adds "Use a consistent orders for the Tailwind CSS classnames, based on the official order" 
Open any file in the `frontend/` that has `className`s, for example, `frontend/src/components/MeetingRoom/Toolbar/Toolbar.tsx`.
Find some `className`s and change their order. For example, in `Toolbar.tsx` example change line 73 to be:
```
<div className="absolute left-0 bottom-0 flex h-[80px] w-full flex-col items-center bg-darkGray-100 p-4 md:flex-row md:justify-between">
```
if you have the right tools configured in VS code, it'll automatically highlight red for you (compared to yellow in `develop`). 
Save the file. Again, if you have the right tools set up, it'll automatically fix this for you.
But if you do not have the tools, save the file and run `yarn lint` in …
=> VIDCS-3453: Use a consistent orders for the Tailwind CSS classnames, based on the official order

frontend/src/components/WaitingRoom/PreviewAvatar/PreviewAvatar.tsx, frontend/src/hooks/tests/useWindowWidth.spec.tsx, frontend/src/hooks/useWindowWidth.tsx
Fixes the avatar overlapping the video container buttons
- go to waiting room, mute video
- resize from minimum width (360px) up to a desktop viewport
- notice there's no overlap with the video container buttons
Resolves [VIDCS-3459](https://jira.vonage.com/browse/VIDCS-3459)
=> VIDCS-3459: On mobile, waiting room preview publisher initials widget is displayed over mute buttons

frontend/src/components/WaitingRoom/ControlPanel/ControlPanel.tsx, frontend/src/components/WaitingRoom/VideoContainer/VideoContainer.tsx, frontend/src/pages/WaitingRoom/WaitingRoom.tsx
Will need to rebase before asking for review. This PR adds the missing loading spinner for mobile devices.
- enter waiting room with a mobile view
- ensure loading spinner is there
- ensure there's no horizontal scrolling
- enter waiting room with desktop view and ensure no weirdness
Resolves [VIDCS-3463](https://jira.vonage.com/browse/VIDCS-3463)
=> VIDCS-3463: On mobile, waiting room loading spinner is not present and horizontal scroll

backend/package.json, frontend/package.json, integration-tests/package.json, package.json
Bumping version to 1.0.3
- n/a, CI passes
Resolves [VIDCS-3478](https://jira.vonage.com/browse/VIDCS-3478)
=> VIDCS-3478: Bump VERA version to 1.0.3

frontend/package.json, yarn.lock
JS SDK to 2.29.2
- n/a, CI passes
Resolves [VIDCS-3477](https://jira.vonage.com/browse/VIDCS-3477)
=> VIDCS-3477: Bump VERA to use JS SDK 2.29.2

frontend/src/components/MeetingRoom/ReportIssue/FeedbackForm/FeedbackForm.tsx
Fixes the styling on the Feedback panel
- apply the following diff
```sh
diff --git a/frontend/src/hooks/useRightPanel.tsx b/frontend/src/hooks/useRightPanel.tsx
index 039923e..a70d866 100644
--- a/frontend/src/hooks/useRightPanel.tsx
+++ b/frontend/src/hooks/useRightPanel.tsx
@@ -22,7 +22,7 @@ export type UseRightPanel = {
*/
const useRightPanel = (): UseRightPanel => {
const [rightPanelState, setRightPanelState] = useState<RightPanelState>({
-    activeTab: 'closed',
+    activeTab: 'issues',
unreadCount: 0,
});
```
- copy snippet above and use terminal command: `pbpaste | git apply`
- check everything looks okay in a variety of viewports
Resolves [VIDCS-3475](https://jira.vonage.com/browse/VIDCS-3475)
[ ] Branch is based …
=> VIDCS-3475: Provide better styling for the `Send` button in the Feedback panel

frontend/src/components/MeetingRoom/ParticipantListItemMenu/ParticipantListItemMenu.spec.tsx, frontend/src/components/MeetingRoom/ParticipantListItemMenu/ParticipantListItemMenu.tsx, frontend/src/components/MeetingRoom/ParticipantListItemMenu/ParticipantPinMenuItem.tsx
- Change menu behaviour to close after clicking
- Change Menu to Popper, in order to allow interaction with the rest of the page while menu is open
- test pinning, menu should close, pinning/un-pinning should happen as expected
- Other items should be clickable while the menu is open
Resolves [VIDCS-3473](https://jira.vonage.com/browse/VIDCS-3473)
[👍 ] Branch is based on `develop` (not `main`).
=> VIDCS-3473: Use Popper instead of Menu and close after clicking pin

frontend/src/components/MeetingRoom/ReportIssueButton/ReportIssueButton.spec.tsx, frontend/src/components/MeetingRoom/ReportIssueButton/ReportIssueButton.tsx
This PR updates the Tooltip for the Report Issue button to be more consistent with other buttons. It also adds tests for the `ReportIssueButton` component.
Hover over the Report Issue button and notice that it says "Open report issue form" -> click on the button.
Hover over the Report Issue button again and notice that it says "Close report issue form".
Notice that this is not the in `develop`. 
Resolves [VIDCS-3491](https://jira.vonage.com/browse/VIDCS-3491)
If yes, which issue? [Issue …
=> VIDCS-3491: Report Issue Tooltip should update based on the state

frontend/src/utils/constants.tsx, frontend/tsdoc.json
This PR changes `@returns` to `@contant` in our `contstants.tsx` file but it also required some changes to how the docs get generated when using `yarn docs` since `@consant` is not one of the built-in ones recognized by the `typedoc` library.
In your terminal, run `yarn docs.`
Notice that there are no warnings in your terminal related to the `@constant` tag - there might be some other warnings but it's not related to this PR.
The docs are going to be generated for you in `frontend/docs` -> open the `index.html` folder. 
Go to `utils` -> `constants.`
Verify that you see the `Constant` on the page. 
Resolves [VIDCS-3505](https://jira.vonage.com/browse/VIDCS-3505)
[ ] Resolves a …
=> VIDCS-3505: Change returns to constant in jsdoc

frontend/src/Context/SessionProvider/session.tsx, frontend/src/components/MeetingRoom/VideoTileCanvas/VideoTileCanvas.tsx, frontend/src/utils/constants.tsx, frontend/src/utils/helpers/getMaxSubscriberOnScreenCount/getMaxSubscriberOnScreenCount.spec.ts, frontend/src/utils/helpers/getMaxSubscriberOnScreenCount/getMaxSubscriberOnScreenCount.ts, frontend/src/utils/helpers/getMaxSubscriberOnScreenCount/index.ts, frontend/src/utils/helpers/getSubscribersToDisplay/getSubscribersToDisplay.ts
This PR adds several fixed for layout numbers
- extra constants to constants file
- account for screenshare publisher when deciding how many subscribers to show (previously ignored)
- up grid subscriber number to 11 (total video 12 with publisher)
- Allow more subscribers in the sidebar when more than 1 subscriber is pinned to the large tile area
- fix bug where pinning in grid view allowed the total grid view number of participants when really it should act the same as screenshare/active-speaker view 
- run locally and test all these cases 😬 
Resolves [VIDCS-3489](https://jira.vonage.com/browse/VIDCS-3489)
[👍  ] Branch is based on `develop` (not `main`).
[ 👎 ] Resolves a `Known Issue`.
[ 👎 ] If yes, did you remove the item from the …
=> VIDCS-3489: Video tile count fixes

frontend/package.json, yarn.lock
axios needs to be upgraded to `^1.8.2` to fix the security issue [mentioned here](https://security.snyk.io/vuln/SNYK-JS-AXIOS-9292519).
Ensure that the functionality that requires the backend works - creating sessions (by joining meeting from two tabs), starting archives. 
Resolves [VIDCS-3511](https://jira.vonage.com/browse/VIDCS-3511)
=> VIDCS-3511: Resolve VERA Security Vulnerability

frontend/src/components/MeetingRoom/ToolbarOverflowButton/ToolbarOverflowButton.tsx, frontend/src/components/MeetingRoom/UnreadMessagesBadge/UnreadMessagesBadge.spec.tsx, frontend/src/components/MeetingRoom/UnreadMessagesBadge/UnreadMessagesBadge.tsx
This PR hides the badge on the menu button when the menu is open and we already see the chat badge. 
before the change:
after the change:
Open one tab in a mobile view, another tab can be in a regular desktop view.
Type up a message in a desktop tab. 
Navigate to the mobile view tab, and notice that there is an unread message badge on the "kebab" menu button.
Notice that the notification on the kebab menu disappears when you click on it.
If you click on the kebab menu again, it shows up again unless you navigate to the Chat tab and "read" the message. 
Resolves [VIDCS-3490](https://jira.vonage.com/browse/VIDCS-3490)
[ ] If yes, did you remove the …
=> VIDCS-3490: Hide the badge on the menu button when the menu is open and we already see the chat badge

vcr-gha.yml
This PR adds OT_API_SECRET to the allowlist to prevent false positives during mend's secret scanning. Hence closing the mend scan issue: https://github.com/Vonage/vonage-video-react-app/issues/82
I found [this which points to ignoring the string](https://github.com/Yelp/detect-secrets/issues/693)
Not sure how we can test this one, I think the only way is to merge it in and hope the issue is closed.
Resolves [VIDCS-3522](https://jira.vonage.com/browse/VIDCS-3522)
=> VIDCS-3522: Fix mend issue Base64 High Entropy String

frontend/src/components/MeetingRoom/EmojiGrid/EmojiGridDesktop.tsx, frontend/src/components/MeetingRoom/EmojiGrid/EmojiGridMobile.tsx, frontend/src/components/MeetingRoom/ToolbarOverflowMenu/ToolbarOverflowMenu.tsx
This PR moves some imports from being imported from `@mui/base` to `@mui/material` to be more consistent with other imports.
Ensure that the "kebab" menu opens up on mobile
Ensure that you are able to send emoji on desktop/mobile.
Resolves [VIDCS-3539](https://jira.vonage.com/browse/VIDCS-3539)
=> VIDCS-3539: Replace some mui/base imports to be more consistent

frontend/src/components/MeetingRoom/EmojiGrid/EmojiGrid.spec.tsx, frontend/src/components/MeetingRoom/EmojiGrid/EmojiGrid.tsx, frontend/src/components/MeetingRoom/EmojiGrid/EmojiGridDesktop.tsx
Resolves an annoying console warning due to the `ref` being `null` on initial render.
- checkout `develop`
- open console
- go to a room
- see warning regarding `anchorEl`
- checkout this branch, `cpettet/vidcs-3548-console-warning`
- open console
- go to a room
- verify there's no `anchorEl` warning
Resolves [VIDCS-3548](https://jira.vonage.com/browse/VIDCS-3548)
=> VIDCS-3548: Console warning regarding anchorEl

backend/package.json, frontend/package.json, integration-tests/package.json, yarn.lock
This PR bumps up VERA version to 2.29.3 and OT version to 2.29.3
n/a, CI passes.
Resolves [VIDCS-3584](https://jira.vonage.com/browse/VIDCS-3584)
Resolves [VIDCS-3587](https://jira.vonage.com/browse/VIDCS-3587)
=> VIDCS-3584: VERA version bump and VIDCS-3587: OT version bump

frontend/src/App.css, frontend/src/pages/WaitingRoom/WaitingRoom.tsx
There was some horizontal scroll on low video height windows caused by the vertical scrollbar. This PR eliminates the vertical scrollbar for *most* screens and eliminates horizontal scroll in all screens.
- go to the locally deployed VERA in a tab on your MBP's screen
- go to a waiting room
- notice there's a horizontal scrollbar, and a vertical scrollbar
- go to a waiting room, again using your MBP's screen
- notice there's no horizontal scrollbar and no vertical scrollbar
- please go through whole flow of: landing --> waiting room --> meeting room --> goodbye
- repeat on mobile
Resolves [VIDCS-3492](https://jira.vonage.com/browse/VIDCS-3492)
[ ] …
=> VIDCS-3492: VERA waiting room has horizontal scroll on MBP screen (but not external monitor)

.github/workflows/deploy-to-vcr.yml, .vcrignore, vcr-gha.yml, vcrGhaBuild.sh
Moving to Build App on VCR.
Also, needed to add VITE_ENABLE_REPORT_ISSUE on `vcrGhaBuild.sh` so that it is accessible on vcr when it builds the app.
This cuts down on the deployment time from 14 to 6 minutes, which has started giving timeout issues issues.
n/a
See, logs of a successful job before the cleanup commit: https://github.com/Vonage/vonage-video-react-app/actions/runs/14245728258/job/39926074602?pr=141
Resolves [VIDCS-3603](https://jira.vonage.com/browse/VIDCS-3603)
If yes, which issue? [Issue …
=> VIDCS-3603: Build app on VCR

.github/workflows/update-screenshots.yml
This PR updates the workflow to ensure the Auto-commit updated screenshots step runs even if earlier steps fail. 
Ex: https://github.com/Vonage/vonage-video-react-app/actions/runs/14385670298/job/40340361059
n/a
Resolves [VIDCS-3641](https://jira.vonage.com/browse/VIDCS-3641)
=> VIDCS-3641: Ensure auto-commit of screenshots runs regardless of previous step failures

.github/workflows/release-notification.yml
This PR adds notification to a Slack channel in the Vonage workspace when a new VERA release is published [https://github.com/Vonage/vonage-video-react-app/releases](here)
We could do a test release to test this or we can wait for 1.1.0 to ship. If the notification is not published then we can dig in deeper. 
Resolves [VIDCS-3651](https://jira.vonage.com/browse/VIDCS-3651)
=> VIDCS-3651: Add notification to Slack channel when a new VERA release is published

frontend/src/Context/PreviewPublisherProvider/usePreviewPublisher/usePreviewPublisher.tsx, frontend/src/Context/user.tsx, frontend/src/components/MeetingRoom/ReduceNoiseTestSpeakers/ReduceNoiseTestSpeakers.tsx, frontend/src/components/MeetingRoom/VideoDevicesOptions/VideoDevicesOptions.tsx, frontend/src/components/WaitingRoom/UserNameInput/UserNameInput.tsx, frontend/src/pages/WaitingRoom/WaitingRoom.tsx, frontend/src/utils/storage.ts
[This previous PR](https://github.com/Vonage/vonage-video-react-app/pull/139) introduced a little util that manages how we interact with `localStorage`. This PR changes that in other places where we interact with the `window.localStorage`. 
Since this PR touches on background blur, noise suppression and username (in the waiting room), please ensure that the settings are saved between the session. For example, if you applied background blur in the meeting room, it should be there the next time you join the waiting/meeting rooms. Same goes for noise suppresion (only available in meeting room) and username.
Resolves [VIDCS-3661](https://jira.vonage.com/browse/VIDCS-3661)
[ ] …
=> VIDCS-3661: Refactor how we interact with window.localStorage 

.eslintrc, backend/routes/feedback.ts, backend/server.ts, backend/tests/session.test.ts, frontend/src/Context/PreviewPublisherProvider/usePreviewPublisher/usePreviewPublisher.tsx, frontend/src/components/MeetingRoom/ReportIssue/FeedbackForm/FilePicker/FilePicker.tsx, frontend/src/components/WaitingRoom/BlurButton/BlurButton.tsx, frontend/src/components/WaitingRoom/CameraButton/CameraButton.tsx, frontend/src/components/WaitingRoom/MicButton/MicButton.tsx, frontend/src/components/WaitingRoom/VideoContainerButton/VideoContainerButton.tsx, frontend/src/hooks/useArchives.tsx, frontend/src/pages/MeetingRoom/MeetingRoom.spec.tsx, frontend/src/pages/WaitingRoom/WaitingRoom.spec.tsx, frontend/tsconfig.json, package.json, yarn.lock
While doing some changes/refactoring in `usePreviewPublisher` I noticed the following:
This PR removes the `ts-expect-error` and makes changes to `deviceDeniedAccess` to better handle the type of permission we are seeking.
Also upgrades the TypeScript version and linter while we at it. Linter needed to be updated because it wasn't compatible with the latest version of TS. 
Ensure that you are getting the expected flow when giving/rejecting access to the hardware.
CI passes (especially linter)
Resolves [VIDCS-3650](https://jira.vonage.com/browse/VIDCS-3650)
[ ] Resolves an item …
=> VIDCS-3650: Remove unused ts-expect-error in VERA usePreviewPublisher

.github/workflows/release-notification.yml
This PR fixes up Slack notify job in VERA deployment process by removing the section that includes the release notes. The reason being is that there is a lot that can go wrong with the section due to formatting and, unfortunately, resulting in a invalid JSON error. Removing this section is not a big deal though since the notification is going to include a button that take straight to the release page. 
example of a failed GitHub action: [here](https://github.com/Vonage/vonage-video-react-app/actions/runs/14580240929/job/40895168578)
not able to until the next release
Resolves [VIDCS-3664](https://jira.vonage.com/browse/VIDCS-3664)
[ ] If yes, did you remove the item from …
=> VIDCS-3664: Fix up Slack notify job in VERA deployment process

.github/workflows/release-notification.yml
[This PR](https://github.com/Vonage/vonage-video-react-app/pull/150) resolved one issue but brought up another. I found another sample that uses a later version of the `slack-github-action` library so hopefully that works.
TBD.
Resolves [VIDCS-3664](https://jira.vonage.com/browse/VIDCS-3664)
=> VIDCS-3664: Fix up Slack notify job in the deployment process

backend/package.json, frontend/package.json, integration-tests/package.json, package.json, yarn.lock
This PR bumps VERA version to 1.1.1 and bumps up OT version to 2.29.4.
n/a
Resolves [VIDCS-3709](https://jira.vonage.com/browse/VIDCS-3709)
Resolves [VIDCS-3712](https://jira.vonage.com/browse/VIDCS-3712)
=> VIDCS-3709: VIDCS-3712: Bump VERA version to 1.1.1 and Bump up OT version to 2.29.4

backend/package.json, backend/routes/session.ts, backend/tests/session.test.ts, backend/types/opentok-jwt-d.ts, backend/videoService/opentokVideoService.ts, backend/videoService/tests/opentokVideoService.test.ts, backend/videoService/tests/vonageVideoService.test.ts, backend/videoService/videoServiceInterface.ts, backend/videoService/vonageVideoService.ts, yarn.lock
This PR implements server-side controls of captions. 
This needs to be tested with both `vonage` and `opentok` as `VIDEO_SERVICE_PROVIDER`s in your `.env` file in the backend. For that, you'll need to have both Vonage applicationId and OpenTok API key.
To test this, you will also need to have Postman installed. 
Once that is done, run the app by doing `yarn dev`.
In Postman, make a `GET` request to `localhost:3345/session/<room_name_of_your_choice>` (notice no trailing slash) - this is going to create a room for you - captions cannot be enabled unless a room has already been created. 
After that, make a `POST` request to `localhost:3345/session/<room_name_of_your_choice>/enableCaptions`.
Notice that you are getting a return that looks something like this:
```
{
"captions": {
"captionsId": …
```
=> VIDCS-3699: Implement server-side controls of captions 

frontend/src/Context/SessionProvider/session.spec.tsx, frontend/src/Context/SessionProvider/session.tsx, frontend/src/types/session.ts, frontend/src/utils/VonageVideoClient/vonageVideoClient.ts
Fixes an issue where the muted indicator was not being updated.
- go to deployed app
- create a room with two participants
- mute the audio for one participant
- notice the other tab does not reflect the changes in the muted indicator
- create a room with two participants
- mute the audio for one participant
- notice the audio muted state change is reflected in the other tab
Resolves [VIDCS-3791](https://jira.vonage.com/browse/VIDCS-3791)
=> VIDCS-3791: Muted indicator does not promptly update when a user mutes

frontend/src/components/MeetingRoom/NameDisplay/NameDisplay.tsx, frontend/src/components/ScreenShareNameDisplay/ScreenShareNameDisplay.tsx, frontend/src/utils/helpers/getBoxStyle.ts
This PR is protecting unsafe values on width/height and maxWidth. 
Values such as `NaN` were throwing a CSS error.
Check that no errors are being thrown in developer console. 
1- Open participants
2- Make screen small
3- You should not see any error:
Resolves [VIDCS-3810](https://jira.vonage.com/browse/VIDCS-3810)
=> VIDCS-3810: Error when components have maxWidth or width with NaN value

frontend/package.json, yarn.lock
This PR bumps up the version of `vonage/client-sdk-video` to the latest currently-available one.
n/a
Resolves [VIDCS-3893](https://jira.vonage.com/browse/VIDCS-3893)
=> VIDCS-3893: vonage/client-sdk-video version bump

backend/package.json, frontend/package.json, integration-tests/package.json, package.json
This PR bumps up  VERA version to 1.2.0.
n/a
Resolves [VIDCS-3890](https://jira.vonage.com/browse/VIDCS-3890)
=> VIDCS-3890: Bump VERA version to 1.2.0

.github/workflows/auto-set-base.yml, .github/workflows/deploy-to-vcr.yml, .github/workflows/lint.yml, .github/workflows/run-tests.yml, .github/workflows/update-screenshots.yml
- Updated `actions/checkout` from v3.0.2 to `v4`
- Updated `actions/setup-node` from v3 to `v4`
These changes should resolve the warning:
[The `save-state` command is deprecated and will be disabled soon.](https://github.com/Vonage/vonage-video-react-app/actions/runs/16036062577)
n/a
Resolves [VIDSOL-101](https://jira.vonage.com/browse/VIDSOL-101)
=> VIDSOL-101: Bump actions to v4 to remove deprecated save-state warnings

backend/package.json, package.json, yarn.lock
This PR adds Yarn resolutions to enforce consistent versions of critical dependencies and address security/vulnerability alerts.
https://github.com/Vonage/vonage-video-react-app/issues/198
https://github.com/Vonage/vonage-video-react-app/issues/197
⚠️ Known Pending Upgrade
`markdown-it` – currently at the latest release, but still flagged with a vulnerability.
No fixed version is available yet.
Will require an update once the maintainers publish a patched release.
CI Pass.
A sanity check on the app functionality.
We cannot test if this actually fixes the vulnerabilities until we merge the PR (may be to the main branch i.e. after the next release ☹️) 
Resolves [VIDSOL-136](https://jira.vonage.com/browse/VIDSOL-136)
[ ] Branch is based on `develop` …
=> VIDSOL-136: Fix vulnerabilities

frontend/package.json, frontend/src/components/MeetingRoom/AudioIndicator/AudioIndicator.spec.tsx, frontend/src/components/MeetingRoom/MutingDialog/MutingDialog.spec.tsx, frontend/src/components/MeetingRoom/ParticipantListItem/ParticipantListItem.spec.tsx, frontend/src/types/session.ts, yarn.lock
This PR bumps up @vonage/client-sdk-video version to `2.31.0`
n/a, CI passes
Resolves [VIDSOL-192](https://jira.vonage.com/browse/VIDSOL-192)
=> VIDSOL-192: Bump up OT version to 2.31.0
